packages:
  - packages/*

catalog:
  '@types/node': 22.12.0
  eslint: 9.39.1
  rimraf: 6.0.1
  tsdown: 0.12.9
  typescript: 5.9.3
  vitest: 3.2.4

patchedDependencies:
  '@changesets/assemble-release-plan@6.0.9': patches/@changesets__assemble-release-plan@6.0.9.patch
