packages:
  - 'packages/*'

catalog:
  typescript: ^5.8.3
  vitest: ^2.1.9
  tsx: ^4.7.1
  '@types/node': ^20.11.17
  '@types/eslint': ^9.6.1
  eslint: ^9.16.0
  '@eslint/js': ^9.16.0
  typescript-eslint: ^8.33.1
  '@typescript-eslint/parser': ^8.33.1
  '@typescript-eslint/rule-tester': ^8.33.1
  '@typescript-eslint/types': ^8.33.1
  '@typescript-eslint/utils': ^8.33.1
