packages:
  - packages/*

catalog:
  '@types/node': 22.12.0
  eslint: 9.39.2
  rimraf: 6.1.2
  tsdown: 0.18.3
  typescript: 5.9.3
  vitest: 4.0.16

patchedDependencies:
  '@changesets/assemble-release-plan@6.0.9': patches/@changesets__assemble-release-plan@6.0.9.patch
