import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcAssetsDir = join(__dirname, '../src/assets');

/**
 * Escapes a string for safe inclusion in a JavaScript string literal.
 * Handles backticks, backslashes, and template literal syntax.
 */
function escapeForTemplate(str) {
  return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

/**
 * Generates a short hash (8 chars) from content for cache-busting.
 */
function generateHash(content) {
  return createHash('sha256').update(content).digest('hex').slice(0, 8);
}

async function buildAssets() {
  try {
    console.log('Building Swagger UI assets...');

    // Create src/assets directory
    await mkdir(srcAssetsDir, { recursive: true });

    // Resolve swagger-ui-dist package path
    const resolvedUrl = import.meta.resolve('swagger-ui-dist');
    const resolvedPath = fileURLToPath(resolvedUrl);
    const swaggerUiDistPath = dirname(resolvedPath);

    // Read swagger-ui.css
    const swaggerUiCss = await readFile(join(swaggerUiDistPath, 'swagger-ui.css'), 'utf-8');
    const cssHash = generateHash(swaggerUiCss);
    const cssTs = `// Auto-generated from swagger-ui-dist
// Do not edit this file directly
export const SWAGGER_UI_CSS = \`${escapeForTemplate(swaggerUiCss)}\`;
`;
    await writeFile(join(srcAssetsDir, 'swagger-ui-css.ts'), cssTs);
    console.log('✓ swagger-ui-css.ts generated');

    // Read swagger-ui-bundle.js
    const swaggerUiJs = await readFile(join(swaggerUiDistPath, 'swagger-ui-bundle.js'), 'utf-8');
    const jsHash = generateHash(swaggerUiJs);
    const jsTs = `// Auto-generated from swagger-ui-dist
// Do not edit this file directly
export const SWAGGER_UI_JS = \`${escapeForTemplate(swaggerUiJs)}\`;
`;
    await writeFile(join(srcAssetsDir, 'swagger-ui-bundle-js.ts'), jsTs);
    console.log('✓ swagger-ui-bundle-js.ts generated');

    // Read swagger-ui-standalone-preset.js
    const swaggerUiStandalonePresetJs = await readFile(
      join(swaggerUiDistPath, 'swagger-ui-standalone-preset.js'),
      'utf-8',
    );
    const standalonePresetJsHash = generateHash(swaggerUiStandalonePresetJs);
    const standalonePresetJsTs = `// Auto-generated from swagger-ui-dist
// Do not edit this file directly
export const SWAGGER_UI_STANDALONE_PRESET_JS = \`${escapeForTemplate(swaggerUiStandalonePresetJs)}\`;
`;
    await writeFile(join(srcAssetsDir, 'swagger-ui-standalone-preset-js.ts'), standalonePresetJsTs);
    console.log('✓ swagger-ui-standalone-preset-js.ts generated');

    // Generate hashes.ts
    const hashesTs = `// Auto-generated from swagger-ui-dist
// Do not edit this file directly
export const SWAGGER_UI_CSS_HASH = '${cssHash}';
export const SWAGGER_UI_JS_HASH = '${jsHash}';
export const SWAGGER_UI_STANDALONE_PRESET_JS_HASH = '${standalonePresetJsHash}';
`;
    await writeFile(join(srcAssetsDir, 'hashes.ts'), hashesTs);
    console.log('✓ hashes.ts generated');

    // Generate index.ts
    const indexTs = `// Auto-generated from swagger-ui-dist
// Do not edit this file directly
export { SWAGGER_UI_CSS } from './swagger-ui-css.js';
export { SWAGGER_UI_JS } from './swagger-ui-bundle-js.js';
export { SWAGGER_UI_STANDALONE_PRESET_JS } from './swagger-ui-standalone-preset-js.js';
export { SWAGGER_UI_CSS_HASH, SWAGGER_UI_JS_HASH, SWAGGER_UI_STANDALONE_PRESET_JS_HASH } from './hashes.js';
`;
    await writeFile(join(srcAssetsDir, 'index.ts'), indexTs);
    console.log('✓ index.ts generated');

    console.log('✓ Assets built successfully');
  } catch (error) {
    console.error('Failed to build assets:', error);
    process.exit(1);
  }
}

buildAssets();
