// Auto-generated from swagger-ui-dist
// Do not edit this file directly
export const SWAGGER_UI_CSS_HASH = 'bc5e8d5c';
export const SWAGGER_UI_JS_HASH = '91393f3b';
export const SWAGGER_UI_STANDALONE_PRESET_JS_HASH = '607f3740';
