// Auto-generated from swagger-ui-dist
// Do not edit this file directly
export const SWAGGER_UI_CSS_HASH = '9e576f83';
export const SWAGGER_UI_JS_HASH = '93b7b086';
export const SWAGGER_UI_STANDALONE_PRESET_JS_HASH = '5ed085e1';
